service: vaccines-data-scraper
plugins:
  - serverless-python-requirements    
frameworkVersion: '2'
provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-west-1
  stage: live
  apiGateway:
    shouldStartNameWithService: true
package:
  include:
    - vaccines-data-scraper.py
    - package/**
functions:
  vaccinationdata:
    handler: vaccines-data-scraper.handle_lambda_request
    events:
      - http:
          path: vaccinationdata.json
          method: get